### PR TITLE
Ag3.0 collection map

### PR DESCRIPTION
**Pull request by cclarkson**
Builds collection map - [Q26](https://quire.io/w/malariagen-ag3.0-paper/26/Figure_with_map_o...?filter=all)

### CODE REVIEW

**Comment by cclarkson** [comment]
Make version with full country (or region e.g. Bioko?) names and with pies scaled to pop size.

**Comment by cclarkson** [comment]
@hardingnj, this is ready for a review now.

**Comment by hardingnj** [comment]
Thanks Chris- I reviewed, making some changes- and made a PR to your fork of the repo.

**Comment by cclarkson** [comment]
@hardingnj  - I think this version is now ready for review, I've added the new legend etc. onto your changes. Thanks for tidying up the code.

**Review by hardingnj — COMMENTED** [review]
Thanks Chris. I'm happy with this code-wise. I'd like to make two changes though:

1. Concept of intermediate samples needs some thought. We need to get across that these samples are intermediate between gambiae / coluzzii, rather than arabiensis/wider complex. Probably needs a bit of thought.
2. I'm working on some common load data functions- so would be nice to use those for the metadata before this is merged.

**Comment by cclarkson** [comment]
Hi @hardingnj. Code here is all now working with the data setup code.

Regarding the intermediate sample labeling, I've changed the legend to clarify gamb x colu intermediates, but this still leaves the single gamb x arab hybrid sample unaccounted for. Any feelings about how you want that one dealt with? Colour-wise we could maybe use a purple (blue+red) for the gamb x colus and black for that single gamb x arab - so it shows up?

**Review by hardingnj — CHANGES_REQUESTED** [review]
Thanks Chris, that was quick! looking good. 

- I like the idea of purple- should be distinguishable too. Let's set the single hybrid as black, I think we can leave it out of legend though(?).
- Let's remove `config.yml` I think it should be superseded by the module now
- Also, the notebook name could be more descriptive. Needs the word "map" in there I think
- Map to be 8" wide, and maybe bump up the dpi to compensate, just for consistency as in `README.md`.

**Comment by cclarkson** [comment]
@hardingnj - purple seems to work okay. You can't really see the single F1 sample in Uganda but I think it is easier to draw attention to this in the figure text anyway.

Figure size and notebook named fixed.

I haven't removed config.yml yet because I need your PR to be merged first.

**Comment by hardingnj** [comment]
Of course! The other PR #6 is merged now, so you should be able to update and remove.

**Comment by cclarkson** [comment]
@hardingnj - ready for review

**Review by hardingnj — APPROVED** [review]
LGTM. In fact I doubt a better sample collection map has ever been made.

**Pull request merged**
